# Generated by Django 4.2.16 on 2024-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
